#!/usr/bin/python3

# CodeX: Dork Scanner feito em Python
# Criador: DevzzMaykon
# Version: 1.0.0
# Sistemas: Linux/Windows
# Licensa: MIT License

try:
    import requests
    import sys

except ImportError as error:
    print(f"\033[1;31m[ERROR] \033[0m\xBB {error}")
    exit()

# Banner:
def codex():
    print("""\033[1;31m
      _|_|_|                  _|            _|      _|
    _|          _|_|      _|_|_|    _|_|      _|  _|
    _|        _|    _|  _|    _|  _|_|_|_|      _|
    _|        _|    _|  _|    _|  _|          _|  _|
      _|_|_|    _|_|      _|_|_|    _|_|_|  _|      _|
  \033[0m
criador: DevzzMaykon
    """)

# Dork:
def scanner():
    codex()

    site = input("site alvo: ") if len(sys.argv) < 2 else sys.argv[1]

    if "https://" not in site:
        print("Modo de uso: https://alvo.com")
        exit()

    lista = ["robots.txt", "wp-admin", "php?id=1", "inurl:phpmyadmin", '/wp-content/uploads/ ext:txt “username” AND “password” | “pwd” | “pw”', "dump.sql"]

    for itens in lista:
        alvo  = f"{site}/{itens}"
        req   = requests.get(alvo)
        req.status_code

        if req.status_code == 200:
            print(f"{alvo} - Status [\033[1;34mON\033[0m]")

        elif req.status_code == 404:
            print(f"{alvo} - Status [\033[1;31mOFF\033[0m]")
try:
    scanner()

except KeyboardInterrupt:
        print("\n\033[1;31m[!] \033[0mExiting...")
        exit()
